import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio made with NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Include shared UI here e.g. a header or sidebar */}
      <header>header test</header>
      <body className={inter.className}>{children}</body>
      <footer>footer test</footer>
    </html>
  )
}
